First commit
alvidediev/GeekBrainsLocalChat pull request #1
Opened 2022-01-29 16:36 UTC by alvidediev

Пытался реализовать то, что Вы оставили на нашей совести, но я так и не смог разобраться в этом. Это не значит, что я не хочу понимать...мне не хватает опыта. Такое чувство, как будто мне чего то не хватает, чтобы втянуться в мир джавы. Возможно...мозгов)

2022-01-30 08:46 UTC, efserg requested changes
Альви, добавьте личные сообщения - хотя бы те, что мы сделали на уроке, остальное все опционально

2022-01-30 08:46 UTC, efserg commented on GBLocalChat/src/main/java/com/example/gblocalchat/Server/ClientHandler.java
> +                        //if (!login.startsWith("login") && !password.startsWith("password")) {
startWith не лучшая идея для логина и пароля

2022-01-30 08:46 UTC, efserg commented on GBLocalChat/src/main/java/com/example/gblocalchat/Server/ClientHandler.java
> +                        //Пытался реализовать проверку вводимых логина и пароля...у меня уже мозг болит.
А мы же вроде в AuthService уже реализовали проверку логина и пароля...

2022-01-30 08:46 UTC, efserg commented on GBLocalChat/src/main/java/com/example/gblocalchat/Server/ClientHandler.java
> +                        sendMessage("Неверный логин или пароль");
Вот же сообщение отсылается. Можно добавить команду, чтобы на неавторизованном клиенте было видно эти сообщения об ошибках

2022-01-30 13:14 UTC, alvidediev reviewed
как то так...)

2022-02-02 16:18 UTC, efserg approved these changes

2022-02-02 21:09 UTC, merged